# Generated by Django 5.1.1 on 2024-10-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directorgeneral',
            options={'ordering': ('nombre',), 'verbose_name': 'Director General', 'verbose_name_plural': 'Directores Generales'},
        ),
        migrations.AlterModelOptions(
            name='laboratorio',
            options={'ordering': ('id',), 'verbose_name': 'Laboratorio', 'verbose_name_plural': 'Laboratorios'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ('-f_fabricacion',), 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RenameField(
            model_name='directorgeneral',
            old_name='dir_nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='laboratorio',
            old_name='lab_nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='producto_nombre',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='directorgeneral',
            name='especialidad',
            field=models.CharField(default='Director Ejecutivo', max_length=64),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='ciudad',
            field=models.CharField(default='Capital', max_length=64),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='pais',
            field=models.CharField(default='Internacional', max_length=64),
        ),
    ]
